export interface Database {
  public: {
    Tables: {
      super_admins: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          created_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          created_at?: string;
        };
      };
      admins: {
        Row: {
          id: string;
          auth_user_id: string;
          shop_id: string | null;
          email: string;
          full_name: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          auth_user_id: string;
          shop_id?: string | null;
          email: string;
          full_name: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          auth_user_id?: string;
          shop_id?: string | null;
          email?: string;
          full_name?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      shops: {
        Row: {
          id: string;
          name: string;
          slug: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      shop_settings: {
        Row: {
          id: string;
          shop_id: string;
          primary_color: string;
          secondary_color: string;
          shop_logo_url: string | null;
          welcome_message: string;
          points_per_dollar: number;
          bronze_points_min: number;
          bronze_multiplier: number;
          silver_points_min: number;
          silver_multiplier: number;
          gold_points_min: number;
          gold_multiplier: number;
          platinum_points_min: number;
          platinum_multiplier: number;
          business_hours?: any | null;
          appointment_duration_minutes?: number | null;
          lead_time_minutes?: number | null;
          bay_count?: number | null;
          tech_count?: number | null;
          timezone?: string | null;
          auto_confirm_services?: string[] | null;
          approval_required_services?: string[] | null;
          updated_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id: string;
          primary_color?: string;
          secondary_color?: string;
          shop_logo_url?: string | null;
          welcome_message?: string;
          points_per_dollar?: number;
          bronze_points_min?: number;
          bronze_multiplier?: number;
          silver_points_min?: number;
          silver_multiplier?: number;
          gold_points_min?: number;
          gold_multiplier?: number;
          platinum_points_min?: number;
          platinum_multiplier?: number;
          business_hours?: any | null;
          appointment_duration_minutes?: number | null;
          lead_time_minutes?: number | null;
          bay_count?: number | null;
          tech_count?: number | null;
          timezone?: string | null;
          auto_confirm_services?: string[] | null;
          approval_required_services?: string[] | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string;
          primary_color?: string;
          secondary_color?: string;
          shop_logo_url?: string | null;
          welcome_message?: string;
          points_per_dollar?: number;
          bronze_points_min?: number;
          bronze_multiplier?: number;
          silver_points_min?: number;
          silver_multiplier?: number;
          gold_points_min?: number;
          gold_multiplier?: number;
          platinum_points_min?: number;
          platinum_multiplier?: number;
          business_hours?: any | null;
          appointment_duration_minutes?: number | null;
          lead_time_minutes?: number | null;
          bay_count?: number | null;
          tech_count?: number | null;
          timezone?: string | null;
          auto_confirm_services?: string[] | null;
          approval_required_services?: string[] | null;
          updated_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      customers: {
        Row: {
          id: string;
          auth_user_id: string | null;
          shop_id: string;
          email: string;
          full_name: string;
          phone: string | null;
          is_admin: boolean;
          tier: string;
          reward_points: number;
          lifetime_spending?: number | null;
          total_lifetime_spending?: number | null;
          total_spent?: number | null;
          has_account: boolean;
          is_deactivated: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          auth_user_id?: string | null;
          shop_id: string;
          email: string;
          full_name: string;
          phone?: string | null;
          is_admin?: boolean;
          tier?: string;
          reward_points?: number;
          lifetime_spending?: number | null;
          total_lifetime_spending?: number | null;
          total_spent?: number | null;
          has_account?: boolean;
          is_deactivated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          auth_user_id?: string | null;
          shop_id?: string;
          email?: string;
          full_name?: string;
          phone?: string | null;
          is_admin?: boolean;
          tier?: string;
          reward_points?: number;
          lifetime_spending?: number | null;
          total_lifetime_spending?: number | null;
          total_spent?: number | null;
          has_account?: boolean;
          is_deactivated?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      vehicles: {
        Row: {
          id: string;
          customer_id: string;
          shop_id: string;
          make: string;
          model: string;
          year: number;
          license_plate: string | null;
          vin: string | null;
          color: string | null;
          notes: string | null;
          picture_url: string | null;
          current_mileage: number;
          last_service_date: string | null;
          last_service_mileage: number | null;
          next_service_due_date: string | null;
          next_service_due_mileage: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          shop_id: string;
          make: string;
          model: string;
          year: number;
          license_plate?: string | null;
          vin?: string | null;
          color?: string | null;
          notes?: string | null;
          picture_url?: string | null;
          current_mileage?: number;
          last_service_date?: string | null;
          last_service_mileage?: number | null;
          next_service_due_date?: string | null;
          next_service_due_mileage?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          shop_id?: string;
          make?: string;
          model?: string;
          year?: number;
          license_plate?: string | null;
          vin?: string | null;
          color?: string | null;
          notes?: string | null;
          picture_url?: string | null;
          current_mileage?: number;
          last_service_date?: string | null;
          last_service_mileage?: number | null;
          next_service_due_date?: string | null;
          next_service_due_mileage?: number | null;
          created_at?: string;
        };
      };
      services: {
        Row: {
          id: string;
          customer_id: string;
          vehicle_id: string | null;
          shop_id: string;
          service_type: string;
          description: string | null;
          amount: number;
          points_earned: number;
          service_date: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          vehicle_id?: string | null;
          shop_id: string;
          service_type: string;
          description?: string | null;
          amount: number;
          points_earned?: number;
          service_date?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          vehicle_id?: string | null;
          shop_id?: string;
          service_type?: string;
          description?: string | null;
          amount?: number;
          points_earned?: number;
          service_date?: string;
          created_at?: string;
        };
      };
      reward_items: {
        Row: {
          id: string;
          shop_id: string;
          name: string;
          description: string | null;
          points_required?: number | null;
          points_cost?: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id: string;
          name: string;
          description?: string | null;
          points_required?: number | null;
          points_cost?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string;
          name?: string;
          description?: string | null;
          points_required?: number | null;
          points_cost?: number | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      reward_redemptions: {
        Row: {
          id: string;
          customer_id: string;
          reward_item_id: string | null;
          shop_id: string;
          points_spent: number;
          status: string;
          created_at: string;
          processed_at: string | null;
        };
        Insert: {
          id?: string;
          customer_id: string;
          reward_item_id?: string | null;
          shop_id: string;
          points_spent: number;
          status?: string;
          created_at?: string;
          processed_at?: string | null;
        };
        Update: {
          id?: string;
          customer_id?: string;
          reward_item_id?: string | null;
          shop_id?: string;
          points_spent?: number;
          status?: string;
          created_at?: string;
          processed_at?: string | null;
        };
      };
      promotions: {
        Row: {
          id: string;
          shop_id: string;
          title: string;
          description: string | null;
          discount_type: string | null;
          discount_value: number | null;
          valid_from: string;
          valid_until: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          shop_id: string;
          title: string;
          description?: string | null;
          discount_type?: string | null;
          discount_value?: number | null;
          valid_from?: string;
          valid_until?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          shop_id?: string;
          title?: string;
          description?: string | null;
          discount_type?: string | null;
          discount_value?: number | null;
          valid_from?: string;
          valid_until?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      customer_promotions: {
        Row: {
          id: string;
          customer_id: string;
          promotion_id: string;
          shop_id: string;
          is_used: boolean;
          used_at: string | null;
          assigned_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          promotion_id: string;
          shop_id: string;
          is_used?: boolean;
          used_at?: string | null;
          assigned_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          promotion_id?: string;
          shop_id?: string;
          is_used?: boolean;
          used_at?: string | null;
          assigned_at?: string;
        };
      };
      appointments: {
        Row: {
          id: string;
          customer_id: string;
          vehicle_id: string | null;
          shop_id: string;
          service_type: string;
          scheduled_date: string;
          scheduled_time: string;
          status: string;
          notes: string | null;
          description: string | null;
          admin_notes: string | null;
          cancelled_reason: string | null;
          cancellation_type: 'cancelled' | 'no-show' | null;
          confirmed_by: string | null;
          confirmed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          customer_id: string;
          vehicle_id?: string | null;
          shop_id: string;
          service_type: string;
          scheduled_date: string;
          scheduled_time: string;
          status?: string;
          notes?: string | null;
          description?: string | null;
          admin_notes?: string | null;
          cancelled_reason?: string | null;
          cancellation_type?: 'cancelled' | 'no-show' | null;
          confirmed_by?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          customer_id?: string;
          vehicle_id?: string | null;
          shop_id?: string;
          service_type?: string;
          scheduled_date?: string;
          scheduled_time?: string;
          status?: string;
          notes?: string | null;
          description?: string | null;
          admin_notes?: string | null;
          cancelled_reason?: string | null;
          cancellation_type?: 'cancelled' | 'no-show' | null;
          confirmed_by?: string | null;
          confirmed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      repair_orders: {
        Row: {
          id: string;
          shop_id: string;
          customer_id: string;
          vehicle_id: string | null;
          appointment_id: string | null;
          status: 'draft' | 'awaiting_approval' | 'approved' | 'declined' | 'closed';
          ro_number: string;
          customer_notes: string | null;
          internal_notes: string | null;
          labor_total: number;
          parts_total: number;
          fees_total: number;
          tax_total: number;
          grand_total: number;
          created_at: string;
          updated_at: string;
          approved_at: string | null;
          closed_at: string | null;
        };
        Insert: {
          id?: string;
          shop_id: string;
          customer_id: string;
          vehicle_id?: string | null;
          appointment_id?: string | null;
          status?: 'draft' | 'awaiting_approval' | 'approved' | 'declined' | 'closed';
          ro_number: string;
          customer_notes?: string | null;
          internal_notes?: string | null;
          labor_total?: number;
          parts_total?: number;
          fees_total?: number;
          tax_total?: number;
          grand_total?: number;
          created_at?: string;
          updated_at?: string;
          approved_at?: string | null;
          closed_at?: string | null;
        };
        Update: {
          id?: string;
          shop_id?: string;
          customer_id?: string;
          vehicle_id?: string | null;
          appointment_id?: string | null;
          status?: 'draft' | 'awaiting_approval' | 'approved' | 'declined' | 'closed';
          ro_number?: string;
          customer_notes?: string | null;
          internal_notes?: string | null;
          labor_total?: number;
          parts_total?: number;
          fees_total?: number;
          tax_total?: number;
          grand_total?: number;
          created_at?: string;
          updated_at?: string;
          approved_at?: string | null;
          closed_at?: string | null;
        };
      };
      repair_order_items: {
        Row: {
          id: string;
          repair_order_id: string;
          item_type: 'labor' | 'part' | 'fee';
          description: string;
          quantity: number;
          unit_price: number;
          total: number;
          taxable: boolean;
          created_at: string;
        };
        Insert: {
          id?: string;
          repair_order_id: string;
          item_type: 'labor' | 'part' | 'fee';
          description: string;
          quantity: number;
          unit_price: number;
          total?: number;
          taxable?: boolean;
          created_at?: string;
        };
        Update: {
          id?: string;
          repair_order_id?: string;
          item_type?: 'labor' | 'part' | 'fee';
          description?: string;
          quantity?: number;
          unit_price?: number;
          total?: number;
          taxable?: boolean;
          created_at?: string;
        };
      };
    };
  };
}

export type SuperAdmin = Database['public']['Tables']['super_admins']['Row'];
export type Admin = Database['public']['Tables']['admins']['Row'];
export type Shop = Database['public']['Tables']['shops']['Row'];
export type ShopSettings = Database['public']['Tables']['shop_settings']['Row'];
export type Customer = Database['public']['Tables']['customers']['Row'];
export type Vehicle = Database['public']['Tables']['vehicles']['Row'];
export type Service = Database['public']['Tables']['services']['Row'];
export type RewardItem = Database['public']['Tables']['reward_items']['Row'];
export type RewardRedemption = Database['public']['Tables']['reward_redemptions']['Row'];
export type Promotion = Database['public']['Tables']['promotions']['Row'];
export type CustomerPromotion = Database['public']['Tables']['customer_promotions']['Row'];
export type Appointment = Database['public']['Tables']['appointments']['Row'];
export type RepairOrder = Database['public']['Tables']['repair_orders']['Row'];
export type RepairOrderItem = Database['public']['Tables']['repair_order_items']['Row'];
